#!/usr/bin/env zsh

# source-safe alias to source a file only if it exists

source-safe() { if [ -f "$1" ]; then source "$1"; fi; }

#
# aliases
#

source-safe "${HOME}/.local/bin/client/alias.sh"

#
# secrets
#

source-safe "{HOME}/.secret.zsh"

#
# GPG
#

source-safe "${HOME}/.local/bin/common/gpg.sh"

#
# OS specific settings
#

if [[ "$OSTYPE" == "darwin"* ]]; then
    source-safe "${HOME}/.local/bin/client/macos.sh"

else
    # Unknown
    :
fi

#
# for working
#

source-safe "${HOME%/}/.work.d/.workrc"

#
# Auto load some functions
#

autoload -Uz \
    dev \
    fgc \
    git-delete-merged-branches \
    chezmoi-cd 

# To customize prompt, run `p10k configure` or edit ~/.config/powerlevel10k/p10k.zsh
[[ ! -f ~/.config/powerlevel10k/p10k.zsh ]] || source ~/.config/powerlevel10k/p10k.zsh
